[WIP] Add Dynamic Allocation on YARN notes.
awesome-spark/spark-gotchas pull request #47
Opened 2016-10-27 13:12 UTC by eliasah

2016-11-29 13:29 UTC, zero323 requested changes
I believe it should go to the Spark Application Deployment. There is nothing that justifies a seperate chapter.

2016-11-29 13:33 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +----------
Can we avoid artificial formatting?

2016-11-29 13:33 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +### Yet Another Dynamic Resource Allocation YA(D)RN
Do we need a sub section here? Do you plan to add more content?

2016-11-29 13:33 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +# Small deployments and dynamic allocation [WIP]
WIP  makes sense for PR title not here. All of that is WIP

2016-11-29 13:33 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +This can lead into an exponential increase of the number of executors in some cases which can break the YARN resource manager. In my case :
I would prefer more authoritative style than personal.

2016-11-29 13:35 UTC, eliasah commented on 11_small_deployments_and_dynamic_allocation.md
> +### Yet Another Dynamic Resource Allocation YA(D)RN
I was thinking about a section for Mesos if it's possible.

2016-11-29 13:35 UTC, eliasah commented on 11_small_deployments_and_dynamic_allocation.md
> +# Small deployments and dynamic allocation [WIP]
I thought that it was needed for the toc generator

2016-11-29 13:36 UTC, eliasah commented on 11_small_deployments_and_dynamic_allocation.md
> +----------
What's artificial formatting ?

2016-11-29 13:37 UTC, eliasah commented on 11_small_deployments_and_dynamic_allocation.md
> +This can lead into an exponential increase of the number of executors in some cases which can break the YARN resource manager. In my case :
I'll review this paragraph.

2016-11-29 13:37 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +### Yet Another Dynamic Resource Allocation YA(D)RN
Wouldn't make more sense h2 for YARN, h2 for Mesos?

2016-11-29 13:38 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +----------
Horizontal line you include with `---------`

2016-11-29 13:40 UTC, zero323 commented on 11_small_deployments_and_dynamic_allocation.md
> +This can lead into an exponential increase of the number of executors in some cases which can break the YARN resource manager. In my case :
I think we should the same in MySQL section. For example "@zero323 comment on that : When you create data frame it fetches schema from database, and the column used has most likely NOT NULL constraint." sounds like a Tweet :)

2016-11-29 13:43 UTC, eliasah commented on 11_small_deployments_and_dynamic_allocation.md
> +This can lead into an exponential increase of the number of executors in some cases which can break the YARN resource manager. In my case :
I don't get your last comment?

2016-12-05 14:50 UTC, zero323 commented
A thought - it would be nice to explain how dynamic allocation affects static objects and PySpark resources.

2017-02-04 11:24 UTC, eliasah commented on 11_small_deployments_and_dynamic_allocation.md
> +This can lead into an exponential increase of the number of executors in some cases which can break the YARN resource manager. In my case :
Just a little reminder about this. You want me to rephrase that sentence ?

2017-02-04 11:39 UTC, zero323 commented
Does it mean you consider this to be ready for merge?

2017-02-04 11:41 UTC, eliasah commented
I'm not sure that's why I'm asking you. I'm not sure that I know what static objects are with python nor if you want me to rephrase the sentence you cited.

2017-02-04 11:42 UTC, zero323 commented
OK.

2017-02-04 11:44 UTC, eliasah commented
Ok what ? You are confusing me. :)

2017-02-04 12:05 UTC, zero323 commented
I acknowledged your statement :)

2017-02-04 12:22 UTC, eliasah commented
Ok then I'm merging

2017-02-04 12:26 UTC, merged